
import pygame
import time
import read_json

pygame.init()
pygame.mixer.init()
C= pygame.mixer.Sound("Sounds/C3.wav")
Cs = pygame.mixer.Sound("Sounds/C3#.wav")
D = pygame.mixer.Sound("Sounds/D3.wav")
#Ds = pygame.mixer.Sound("Sounds/D3#.wav")
E = pygame.mixer.Sound("Sounds/E3.wav")
F = pygame.mixer.Sound("Sounds/F3.wav")
Fs = pygame.mixer.Sound("Sounds/F3#.wav")
G = pygame.mixer.Sound("Sounds/G3.wav")
Gs = pygame.mixer.Sound("Sounds/G3#.wav")
A = pygame.mixer.Sound("Sounds/A3.wav")
As = pygame.mixer.Sound("Sounds/A3#.wav")
B = pygame.mixer.Sound("Sounds/B3.wav")

F.play()
time.sleep(0.44)
F.play()
time.sleep(0.43)
F.play()
time.sleep(0.41)
A.play()
time.sleep(0.41)
F.play()
time.sleep(0.45)
C.play()
time.sleep(0.85)
F.play()
time.sleep(0.31)
F.play()
time.sleep(0.16)
E.play()
time.sleep(0.50)
Cs.play()
time.sleep(0.19)
F.play()
time.sleep(0.61)
E.play()
time.sleep(0.35)
E.play()
time.sleep(1.52)
