import pygame
import time
import read_json

pygame.init()
pygame.mixer.init()
C= pygame.mixer.Sound("Sounds/C3.wav")
Cs = pygame.mixer.Sound("Sounds/C3#.wav")
D = pygame.mixer.Sound("Sounds/D3.wav")
#Ds = pygame.mixer.Sound("Sounds/D3#.wav")
E = pygame.mixer.Sound("Sounds/E3.wav")
F = pygame.mixer.Sound("Sounds/F3.wav")
Fs = pygame.mixer.Sound("Sounds/F3#.wav")
G = pygame.mixer.Sound("Sounds/G3.wav")
Gs = pygame.mixer.Sound("Sounds/G3#.wav")
A = pygame.mixer.Sound("Sounds/A3.wav")
As = pygame.mixer.Sound("Sounds/A3#.wav")
B = pygame.mixer.Sound("Sounds/B3.wav")

F.play()
time.sleep(0.44)
E.play()
F.play()
Fs.play()
time.sleep(0.43)
E.play()
F.play()
G.play()
time.sleep(0.41)
A.play()
E.play()
As.play()
F.play()
time.sleep(0.41)
F.play()
Gs.play()
G.play()
E.play()
time.sleep(0.45)
C.play()
F.play()
G.play()
B.play()
time.sleep(0.85)

F.play()
time.sleep(0.31)

E.play()
time.sleep(0.50)

Cs.play()
D.play()
time.sleep(0.19)

F.play()
E.play()
Fs.play()
G.play()
time.sleep(0.61)

E.play()
time.sleep(0.35)

E.play()
A.play()
time.sleep(1.52)
